---
- hosts: manage1
  tasks:
    - name: install package
      include_tasks: install_package.yml paramter={{ item }}
      with_items:
        - httpd
        - php
        - mariadb
      notify:
        - restart service

    - name: copy config files
      include_tasks: copy_config.yml
      notify:
        - restart service

    - name: copy web contents file
      include_tasks: copy_webcontents.yml

    - name: set port
      include_tasks: set_port.yml parameter="8080/tcp"

    - name: start service
      include_tasks: start_svc.yml

  handlers:
    - name: restart service
      include_tasks: restart_svc.yml

