---
- hosts: manage1
  tasks:
    - name: task1
      command: sleep 10
      async: 60
      poll: 0
      register: sleeper

    - name: task2
      ping:

    - name: resync-task
      async_status:
        jid: "{{ sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30

    - name: Task4
      debug:
        msg: "DONE"
